# Generated by Django 4.0.1 on 2022-02-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payless', '0002_product_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='online_partner',
            field=models.TextField(default='jiomart'),
        ),
    ]
