# Generated by Django 4.0.1 on 2022-02-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payless', '0003_product_online_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='groceryHeadings',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
