# Generated by Django 4.0.1 on 2022-02-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payless', '0004_groceryheadings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='groceryHeadings',
            new_name='Grocery_Headings',
        ),
    ]
