# Generated by Django 4.0.1 on 2022-02-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payless', '0005_rename_groceryheadings_grocery_headings'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery_headings',
            name='name',
            field=models.TextField(default='Onion'),
        ),
    ]
