# Generated by Django 4.0.1 on 2022-02-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payless', '0006_grocery_headings_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(default='Groceries'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category_1',
            field=models.TextField(default='Fruits & Vegetables'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category_2',
            field=models.TextField(default='Fresh Vegetables'),
        ),
    ]
