# Generated by Django 4.0.1 on 2022-02-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payless', '0007_alter_product_category_alter_product_sub_category_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='grocery_headings',
            name='image',
            field=models.ImageField(default='null', upload_to='payless/images/'),
        ),
    ]
