# Generated by Django 4.0.1 on 2022-02-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payless', '0009_product_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery_headings',
            name='category',
            field=models.TextField(default='Fresh Vegetables'),
        ),
    ]
