# Generated by Django 4.0.1 on 2022-02-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payless', '0010_grocery_headings_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.TextField(default='/payless/images/no image.jpg'),
        ),
    ]
