# Generated by Django 4.0.1 on 2022-02-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payless', '0012_rename_image_url_product_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='/payless/images/no image.jpg'),
        ),
    ]
