# Generated by Django 4.0.1 on 2022-03-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payless', '0013_remove_product_product_image_url_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='normalized_category',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='normalized_name',
            field=models.TextField(default=''),
        ),
    ]
